### ISSUE TITLE
evm does not install emacs-24.3

### ISSUE THREAD

**Issue by ryantm** [rejeep/evm#23]
```
ryantm@ryantm0j132 ~/.evm (master)$ uname -a
Linux ryantm0j132 3.12.6-1-ARCH #1 SMP PREEMPT Fri Dec 20 19:39:00 CET 2013 x86_64 GNU/Linux

ryantm@ryantm0j132 ~ (master)$ evm install emacs-24.3

[1A[----------------------------------------------------------------------------------------------------] 100%

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/home/ryantm/.evm/lib/evm/builder.rb:112:in `instance_eval': No such file or directory - /usr/local/evm/tmp/emacs-24.3 (Errno::ENOENT)
    from /home/ryantm/.evm/lib/evm/builder.rb:99:in `run_command'
    from /home/ryantm/.evm/lib/evm/builder.rb:61:in `configure'
    from (eval):15:in `block (2 levels) in build!'
    from /home/ryantm/.evm/lib/evm/builder.rb:53:in `install'
    from (eval):14:in `block in build!'
    from /home/ryantm/.evm/lib/evm/builder.rb:14:in `recipe'
    from (eval):1:in `build!'
    from /home/ryantm/.evm/lib/evm/builder.rb:112:in `instance_eval'
    from /home/ryantm/.evm/lib/evm/builder.rb:112:in `build!'
    from /home/ryantm/.evm/lib/evm/package.rb:40:in `install!'
    from /home/ryantm/.evm/lib/evm/command/install.rb:18:in `initialize'
    from /home/ryantm/.evm/lib/evm/cli.rb:27:in `new'
    from /home/ryantm/.evm/lib/evm/cli.rb:27:in `parse'
    from /home/ryantm/.evm/bin/evm:7:in `<main>'
```

**Comment by bradyt** [comment]
Manually downloading `emacs-24.3.tar.gz` into `/usr/local/evm/tmp/` seems to fix.

**Comment by bradyt** [comment]
Ah, I bet this is a partial download issue. The same `.tar.gz` file has 0 bytes during download. I imagine some of us may quit download before finishing, then next attempt looks at the partial download. A progress bar may help prevent people from quitting the download. Or is there a way to continue a partial download on next attempt? And the checksum alone may force `evm` to start over at least, instead of trying to apply `tar`. A quick fix might be check if file is zero bytes.
