### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by nlamirault** [rejeep/evm#41]
After installling evm, i can't list emacs available versions :

```bash
$ curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
Successfully installed EVM! Now, add the evm binary to your PATH.
  export PATH="/home/nlamirault/.evm/bin:$PATH"
```

```bash
$ evm list
emacs-24.3-bin
emacs-24.1
emacs-24.3
emacs-23.4-bin
emacs-24.2-bin
emacs-git-snapshot
emacs-24.1-bin
emacs-23.4
emacs-24.2
```

```bash
$ evm install emacs-24.3-bin
Successfully installed emacs-24.3-bin
```

```bash
$ evm list
emacs-24.3-bin [I]
emacs-24.1
emacs-24.3
emacs-23.4-bin
emacs-24.2-bin
emacs-git-snapshot
emacs-24.1-bin
emacs-23.4
emacs-24.2
```
```bash
$ evm use emacs-24.3-bin
```

```bash
$ evm list
/home/nlamirault/.evm/lib/evm/package.rb:74:in `initialize': undefined (?...) sequence: /\/usr\/local\/evm\/?(?<current>[^\/]+)\/.+/ (RegexpError)
	from /home/nlamirault/.evm/lib/evm/package.rb:74:in `new'
	from /home/nlamirault/.evm/lib/evm/package.rb:74:in `current'
	from /home/nlamirault/.evm/lib/evm/package.rb:10:in `current?'
	from /home/nlamirault/.evm/lib/evm/command/list.rb:7:in `initialize'
	from /home/nlamirault/.evm/lib/evm/command/list.rb:6:in `each'
	from /home/nlamirault/.evm/lib/evm/command/list.rb:6:in `initialize'
	from /home/nlamirault/.evm/lib/evm/cli.rb:31:in `new'
	from /home/nlamirault/.evm/lib/evm/cli.rb:31:in `parse'
	from /home/nlamirault/.evm/bin/evm:7
```

**Comment by rejeep** [comment]
Closing this as I'm not going to add 1.8 support.
