### ISSUE TITLE
ECONNRESET from Travis?

### ISSUE THREAD

**Issue by jorgenschaefer** [rejeep/evm#51]
My Travis builds have been failing randomly for the last weeks because evm has trouble downloading images:

```
$ curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
$ export PATH="$HOME/.evm/bin:$PATH"
$ evm install $EVM_EMACS --use
/home/travis/.evm/lib/evm/builder.rb:114:in `instance_eval': Connection reset by peer (Errno::ECONNRESET)
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/openssl/buffering.rb:174:in `read_nonblock'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/protocol.rb:141:in `rbuf_fill'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/protocol.rb:92:in `read'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:2756:in `read_body_0'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:2711:in `read_body'
	from /home/travis/.evm/lib/evm/remote_file.rb:24:in `block (2 levels) in download'
	from /home/travis/.evm/lib/evm/remote_file.rb:58:in `call'
	from /home/travis/.evm/lib/evm/remote_file.rb:58:in `block (2 levels) in request'
	from /home/travis/.evm/lib/evm/remote_file.rb:55:in `call'
	from /home/travis/.evm/lib/evm/remote_file.rb:55:in `block in request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1323:in `block (2 levels) in transport_request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:2672:in `reading_body'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1322:in `block in transport_request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1294:in `request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1287:in `block in request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:746:in `start'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1285:in `request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1196:in `request_get'
	from /home/travis/.evm/lib/evm/remote_file.rb:52:in `request'
	from /home/travis/.evm/lib/evm/remote_file.rb:57:in `block in request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1323:in `block (2 levels) in transport_request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:2672:in `reading_body'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1322:in `block in transport_request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1294:in `request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1287:in `block in request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:746:in `start'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1285:in `request'
	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1196:in `request_get'
	from /home/travis/.evm/lib/evm/remote_file.rb:52:in `request'
	from /home/travis/.evm/lib/evm/remote_file.rb:21:in `block in download'
The command "evm install $EVM_EMACS --use" failed and exited with 1 during .
Your build has been stopped.
```

Any idea what might be causing this? It works most of the time, but I have regular build errors because of this.

**Comment by rejeep** [comment]
No idea actually, have never seen this error. It might be a good idea to implement retries (for example http://stackoverflow.com/questions/9204920/how-to-catch-error-connection-reset-by-peer-errnoeconnreset) though.

**Comment by rejeep** [comment]
Is this still an issue? Anyways, the download mechanism is replaced, so hopefully that'll solve it. Reopen this issue if not.

**Comment by jorgenschaefer** [comment]
I have not seen this in a while, so closing is fine with me. I'll come along if I see it again. :-)

**Comment by mucsi96** [comment]
Hi, Today I got the issue again. https://travis-ci.org/mucsi96/nightwatch-cucumber/builds/126993688
